paperJarUrl=https://fill-data.papermc.io/v1/objects/6c59eefe2752f97ee79f83ad0a61fe14865a0976e4ac06597f53de6c44afd6c5/paper-26.1.2-70.jar
guavaJarUrl=https://repo1.maven.org/maven2/com/google/guava/guava/33.6.0-jre/guava-33.6.0-jre.jar
jomlJarUrl=https://github.com/JOML-CI/JOML/releases/download/1.10.9/joml-1.10.9.jar
protocolLibJarUrl=https://github.com/dmulloy2/ProtocolLib/releases/download/dev-build/ProtocolLib.jar
pluginCommonRepoUrl=https://github.com/WOODEN-CHEST/PluginCommon.git
